### ISSUE TITLE
Fix microsite deploy error due to latest mdoc release changes

### ISSUE THREAD

**Issue by softinio** [zio/zio-zmx#39]
This is the error: 

```
/tmp/docusaurus2351590966069628621install_ssh.sh: line 4: GITHUB_DEPLOY_KEY: unbound variable
[error] java.lang.AssertionError: assertion failed: command returned 1: [/tmp/docusaurus2351590966069628621install_ssh.sh]
[error] 	at scala.Predef$.assert(Predef.scala:223)
[error] 	at mdoc.DocusaurusPlugin$XtensionProcess.execute(DocusaurusPlugin.scala:163)
[error] 	at mdoc.DocusaurusPlugin$.$anonfun$projectSettings$5(DocusaurusPlugin.scala:115)
[error] 	at mdoc.DocusaurusPlugin$.$anonfun$projectSettings$5$adapted(DocusaurusPlugin.scala:96)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (docs / docusaurusPublishGhpages) java.lang.AssertionError: assertion failed: command returned 1: [/tmp/docusaurus2351590966069628621install_ssh.sh]
[error] Total time: 22 s, completed Jun 14, 2020 8:12:17 PM

Exited with code exit status 1
```

sample circleci failure: https://circleci.com/gh/zio/zio-zmx/493

This issue has occured due to this change in latest mdoc release: 

https://github.com/scalameta/mdoc/pull/352/files

## Correction needed ##

In circleci env building microsite we need to set `GITHUB_DEPLOY_KEY` environment variable to the base64 encoded private SSH key that we setup for the microsite deploys. 

i.e get the key by doing for example: `cat .ssh/id_zmx | base64 | pbcopy`

**Comment by softinio** [comment]
Done.
